# Autogenerated wrapper script for github_release_jll for x86_64-w64-mingw32
export github_release

JLLWrappers.@generate_wrapper_header("github_release")
JLLWrappers.@declare_executable_product(github_release)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        github_release,
        "bin\\github-release.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
